- name: Installing 7zip
  hosts: all

  tasks:
    - name: Download the Apache installer
      win_get_url:
        url: https://www.7-zip.org/a/7z2301-x64.exe
        dest: C:\ansible_examples\httpd-2.2.25-win32-x86-no_ssl.msi

    - name: Install 7zip
      win_package:
        path: C:\ansible_examples\7z2301-x64.exe
        state: present